### ISSUE TITLE
There is no env example

### ISSUE THREAD

**Issue by Damontools32** [sabber-slt/youtube-subtitle-generator#1]
As you said in description "put your bot token Inside env.example and rename it to .env " but there is no env.example . What Shall I do?

**Comment by sabber-slt** [comment]
Thank you for letting me know. I will definitely fix it.
After cloning, you just need to change the name of the file env.local to env and put your api keys there.

**Comment by Damontools32** [comment]
Thank you for your respond.
But in env.lical there are only two section one for port and the other one is for deepl API key .
Where shall I put my bot token?
